prompt create_s_developer
DECLARE
	l_EXIST NUMBER;
BEGIN
	SELECT count(*) into l_EXIST
	FROM USER_SEQUENCES
	WHERE SEQUENCE_NAME = 'S_DEVELOPER';
	
	if l_EXIST = 0 then
		EXECUTE IMMEDIATE 'CREATE SEQUENCE S_DEVELOPER MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER ';
	end if;
END;
/