CREATE TABLE "T_SEC_USER" (
"ID" NUMBER NOT NULL ENABLE, 
"GUID" RAW(16) NOT NULL ENABLE, 
"NAME" VARCHAR2(255) NOT NULL ENABLE, 
"EMAIL" VARCHAR2(255), 
"PHONENUMBER" VARCHAR2(50), 
"SKILLSET" VARCHAR2(4000),
"HOBBY" VARCHAR2(4000)
)
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "USERS" 